PrefectHQ/miter-design

CHANGELOG.md, src/styles/base/_spacing.scss
This PR:
~~- [ ] adds new tests or updates existing tests (or hasn't, for reasons explained below)~~
~~- [ ] strictly follows the design spec (if one exists)~~
~~- [ ] adheres to [a11y guidelines](https://www.a11yproject.com/checklist/)/[WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) guidelines where applicable; this can be tested using Lighthouse (native in Chrome dev tools or as a plugin for other browsers) and with accessibility reports in Firefox~~
~~- [ ] Chrome~~
~~- [ ] Firefox~~
~~- [ ] Edge~~
~~- [ ] Safari~~
Refactor of _spacing.scss for the following purposes
1. Group breakpoint styles together in the same media query to …
=> Refactor Spacing CSS

src/components/Select/Select.vue, src/demo/sections/Selects.vue, src/styles/components/radio.scss, src/styles/components/select.scss
This PR:
- allows customizing selector height/width
- selectors that open up now have flipped arrow icons to reflect this
- fixes an issue where selector lists had a lower z-index than other elements on the page (and so would be hidden)
=> Select dimensions

CHANGELOG.md, src/demo/sections/Cards.vue, src/styles/components/card.scss
This PR:
Fixes flex-box values and bad height inheritance on the main section when both a header and footer were applied.
=> Fixes an issue where the main content section wasn't correctly flexed

CHANGELOG.md, package-lock.json, package.json, src/components/Select/OptionLabel.vue, src/components/Select/Select.stories.js, src/components/Select/Select.vue, src/components/Select/SimpleSelect.vue
=> Select slot fixes

vite.config.ts
=> Fix build warning because of using named exports.

.github/workflows/release.yml
Also requires approval for publishing new versions using the "prod" github environment
=> Update Release workflow to create a git tag, github release, and publish to npm

.github/workflows/release.yml
=> Add the github token to the create release job

src/types/index.d.ts
This PR:
~~- [ ] adds new tests or updates existing tests (or hasn't, for reasons explained below)~~
~~- [ ] strictly follows the design spec (if one exists)~~
~~- [ ] adheres to [a11y guidelines](https://www.a11yproject.com/checklist/)/[WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) guidelines where applicable; this can be tested using Lighthouse (native in Chrome dev tools or as a plugin for other browsers) and with accessibility reports in Firefox~~
Fixes an issue where the typescript module declaration was incorrect leading to missing types in downstream imports.
=> Fix module declaration

src/components/Tags/Tags.vue
=> Update Tags gap

package.json, src/components/Toast/index.ts
=> added index.ts file for toast component

package.json, src/index.ts
- added index.ts file for toast component
- including toast component in higher level index.ts file
- addded toast component to higher level index.ts file
This PR:
=> export toast

src/components/DataTable/DataTable.spec.js, src/components/DataTable/DataTable.spec.ts
This PR:
Related to #137 
Adds tests
=> DataTable tests

src/styles/abstracts/_variables.scss
Added a couple additional custom properties for sass variables for the logs release
=> Add some custom properties that were missing

package.json
=> release 0.1.20

CHANGELOG.md, package.json, src/styles/components/input.scss, src/styles/components/tag.scss
This PR:
Update alignment for tag and input to make them properly leveled with text
Closes prefectHQ/nebula-ui#36
=> Update alignment for tag and input + Release 0.1.21

CHANGELOG.md, src/components/Input/Input.spec.js, src/components/Input/Input.vue, src/demo/sections/Inputs.vue
=> add input inputs autocomplete, id and name

src/components/Input/Input.spec.js, src/components/Input/Input.vue, src/demo/sections/Inputs.vue, src/styles/components/input.scss
This PR:
This PR updates the `Input` component to match designs that removed horizontal padding. It also converts the component CSS to BEM for maintainability.
=> Input updates

CHANGELOG.md, src/styles/components/input.scss
This PR:
Update inputs styles in accordance with Nebula designs that will become a default
Closes prefectHQ/nebula-ui#58
=> Update inputs styles

src/components/Panels/Panel.vue, src/components/Panels/PanelContainer.vue, src/components/Panels/index.ts, src/demo/sections/PanelsSection.vue, src/demo/sections/PanelsSectionPanel.vue, src/demo/sections/PanelsSectionPanelTwo.vue, src/demo/views/Components.vue, src/index.ts, src/plugins/Panel/index.ts
Panels are a new UI element similar to the already existing Drawer. Panels were designed to with with the panels vue plugin which is also part of this PR. The goal of this PR was to not only make panels look and function correctly but to make using them easy.
[Panel Design from Figma](https://www.figma.com/file/JomY9jsgJdal9wfPBtpWkY/UI?node-id=3538%3A133525)
By installing miter the `Panel` plugin is also installed.
To show a panel first create a panel component. A panel component should use the `m-panel` component as its layout. Using the slots and slot scopes from `m-panel` you can do things like add a title, content, and actions. You can also use the `close` and `exit` methods which are scoped to each slot. 
```
<template>
<m-panel>
<template #title>
{{ flow.name }}
</template>
<div> …
```
=> Feature: Panels

src/components/Tag/Tag.spec.js, src/components/Tag/Tag.stories.js, src/components/Tag/Tag.vue, src/demo/sections/Tag.vue, src/styles/components/tag.scss
=> Feature: Add optional miter prop to M-Tag

package.json, src/components/Panels/Panel.vue
Fixes some css issues with slotted styles for the new panels
=> BugFix: Panel slotted styles

package.json, src/index.ts, src/plugins/Panel/index.ts
=> Feature: added and exporting InjectionKey for showPanel function

src/components/Panels/PanelContainer.vue, src/index.ts, src/plugins/Panel/index.ts
exporting the panel queue for use in other projects
=> Export panel queue

src/components/Select/Select.vue, src/components/Toast/ToastContainer.vue, src/plugins/Toast/index.ts, src/styles/components/popover.scss
Default z-index's should be a lot more usable and individual projects can easily customize them via custom properties.
=> Feature: Add layer custom properties for z-indexes

src/styles/components/toast.scss
https://github.com/PrefectHQ/orion/issues/1319
=> Feature: updated styles for toast messages

src/components/Tag/Tag.stories.js, src/styles/components/checkbox.scss
Fixes safari bug
https://prefect-squad.monday.com/boards/2335616877/pulses/2400686481
=> BugFix: Checkbox safari fix

CHANGELOG.md, src/components/DatePicker/DatePicker.vue, src/components/Tags/Tags.spec.js, src/components/Tags/Tags.vue, src/demo/sections/Tags.vue
Replace '--' with 'No Tags' when no tags are provided
[monday:2466940267](https://prefect-squad.monday.com/boards/2335616877/pulses/2466940267)
This PR:
=> Replace '--' with 'No Tags' when no tags
